### ISSUE TITLE
question: are long/complex ffmpeg process supported?

### ISSUE THREAD

**Issue by eladg** [binoculars/aws-lambda-ffmpeg#15]
Hi guys, some AWS/Lambda functionalities are really vague to me, reaching out for help.

What are the limits of execution time of FFmpeg on Lambda? If I would like to overlay 2 videos together which requires transcoding, will aws-lambda-ffmpeg support such operation? Will Lambda prevent the long ffmpeg task from running?

I've looked over at [Elastic Transcoder](https://aws.amazon.com/elastictranscoder/) and other services like Zencoder and encoding.com. Lots of the functionalities we're using are missing (such as FFmpeg filters and more)... I'm planning to build my own little service and thought Lambda and this package may help but I'm not certain about performance or if it's possible at all.

Cheers

**Comment by binoculars** [comment]
Hi @eladg 

AWS Lambda currently limits total execution time per function call to 300 seconds (see [AWS Lambda Limits](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) in the docs). Although this function isn't configured to overlay two videos, if you know how to do this with command line arguments, it would be almost trivial to modify this function to perform that task, with a few caveats. There are several factors at play, so the answer is not exactly straightforward, but I'll give it a shot.

These factors include:
- **The memory size you choose for your lambda function.** Memory and CPU speed are bundled together, so the higher memory setting you choose, the faster the function will process the video. I've set the default to the highest at 1538 MB, because this is mostly a CPU-intensive function.
- **The duration of the videos.** If your videos are several hours long, this will likely not work. In this case, I would probably go with FFmpeg running in ECS and an SQS queue, or maybe even Elastic Beanstalk.
- **The size of the videos.** If you're dealing with files over 512 MB, you'll easily exceed the ephemeral disk capacity limit.
- **The computational complexity of the editing process.** This may push the limits of the 300 second execution time.

I would guess that most third party services are probably geared toward the masses like transcoding videos into different formats and sizes. I don't know, off-hand, of any services that do what you're asking.

Have you considered do any of this purely on the client side? [This is just one great example of filters in the browser](http://codepen.io/chriscoyier/pen/zbakI). I believe there are [other examples using three.js](http://threejs.org/examples/webgl_materials_video.html) if you want to get creative :smile:.

Does that help you?

**Comment by eladg** [comment]
Thank you @binoculars! really good insights.
