### ISSUE TITLE
[Documentation] Having trouble understanding how to set it up on AWS

### ISSUE THREAD

**Issue by mlumbroso** [binoculars/aws-lambda-ffmpeg#44]
Hello,

Sorry if that seems basic, but I didn't really understand everything on the process to install the function in AWS Lambda.

1) Step 4. Create your function code's storage location (or choose an existing one) : does that mean creating the Lambda function distantly ? (seems unlikely since it's the purpose of this repo)
Or put it in a local file (if so, where) ?
2) Step 5. I didn't understand why on config_samples/ samples there is no file for AWS ?

Thanks for your great work :)

**Comment by binoculars** [comment]
You need a bucket to upload the CloudFormation template and zipped Lambda code to. The Gulp tasks deploy the function through CloudFormation template. Side note: you don't have to actually build anything, just look in the releases and you can download those files and do it all manually in the AWS console or with the AWS CLI.

The gulp tasks also use environment variables to set the Lambda's environment variables (basically 1-for-1)

There's no config sample for AWS, because it uses environment variables now. GCF (and previously Lambda) don't let you specify environment variables, so you need to include a config file.

**Comment by mlumbroso** [comment]
Great, got it, maybe this should be added to the documentation so that it's crystal clear for everyone !
