### ISSUE TITLE
Inline Coding on Lambda and Documentation

### ISSUE THREAD

**Issue by kevinwu** [binoculars/aws-lambda-ffmpeg#58]
Hi,

I am editing my code inline on Lambda. Is there a way I can also include and use this library with that method?

Alternatively, if that is not possible and I have to upload a zip file to Lambda, could you please expand your documentation to include code samples? Unless I have missed something, there is no place where you describe using code examples how to use your library to for example convert mp4 from s3 to mp3, which you would send back to s3.

Looking forward to your reply, thanks.

**Comment by binoculars** [comment]
No, you cannot edit inline, because it depends on external files (i.e. the FFmpeg and FFprobe executables).

If you follow the README, you just need to set some environment variables, then run the appropriate gulp commands. It should be all there in the README.
https://github.com/binoculars/aws-lambda-ffmpeg#environment-settings

Travis builds and runs the function:
https://github.com/binoculars/aws-lambda-ffmpeg/blob/develop/.travis.yml

**Comment by binoculars** [comment]
Stale issue, closing
